{
    "active_lock_reason": "too heated",
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "I am getting the error: \r\n```\r\nb'device'\r\nTraceback (most recent call last):\r\n  File \"autoroot.py\", line 123, in <module>\r\n    install_firmware(dloadfirmware, device)\r\n  File \"autoroot.py\", line 120, in install_firmware\r\n    print(device.Push(os.path.join(d, 'Software', 'dload'), storage+'/dload', timeout_ms=100000))\r\n  File \"/home/penn/python-adb/adb/adb_commands.py\", line 269, in Push\r\n    progress_callback=progress_callback)\r\n  File \"/home/penn/python-adb/adb/adb_commands.py\", line 280, in Push\r\n    mtime=int(mtime), progress_callback=progress_callback, **kwargs)\r\n  File \"/home/penn/python-adb/adb/filesync_protocol.py\", line 149, in Push\r\n    cnxn.Send(b'DATA', data)\r\n  File \"/home/penn/python-adb/adb/filesync_protocol.py\", line 207, in Send\r\n    self._Flush()\r\n  File \"/home/penn/python-adb/adb/filesync_protocol.py\", line 254, in _Flush\r\n    self.adb.Write(self.send_buffer[:self.send_idx])\r\nAttributeError: 'NoneType' object has no attribute 'Write'\r\n```\r\n\r\nI've confirmed that the path I'm pushing to exists. I'm pushing a directory to another directory. I'm using Ubuntu 18.04. I am able to use the Shell command fine.\r\n\r\nThis looks similar to #125 except in Push not Pull.\r\n\r\nThe adbd is running as root on the phone, as is python3 on my PC.",
    "closed_at": "2018-11-13T17:44:37Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/306100?v=4",
        "events_url": "https://api.github.com/users/fahhem/events{/privacy}",
        "followers_url": "https://api.github.com/users/fahhem/followers",
        "following_url": "https://api.github.com/users/fahhem/following{/other_user}",
        "gists_url": "https://api.github.com/users/fahhem/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/fahhem",
        "id": 306100,
        "login": "fahhem",
        "node_id": "MDQ6VXNlcjMwNjEwMA==",
        "organizations_url": "https://api.github.com/users/fahhem/orgs",
        "received_events_url": "https://api.github.com/users/fahhem/received_events",
        "repos_url": "https://api.github.com/users/fahhem/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/fahhem/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/fahhem/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/fahhem"
    },
    "comments": 10,
    "comments_url": "https://api.github.com/repos/google/python-adb/issues/134/comments",
    "created_at": "2018-11-05T11:33:47Z",
    "events_url": "https://api.github.com/repos/google/python-adb/issues/134/events",
    "html_url": "https://github.com/google/python-adb/issues/134",
    "id": 377360112,
    "labels": [],
    "labels_url": "https://api.github.com/repos/google/python-adb/issues/134/labels{/name}",
    "locked": true,
    "milestone": null,
    "node_id": "MDU6SXNzdWUzNzczNjAxMTI=",
    "number": 134,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/google/python-adb/issues/134/reactions"
    },
    "repository_url": "https://api.github.com/repos/google/python-adb",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/google/python-adb/issues/134/timeline",
    "title": "Push: NoneType has no attribute Write",
    "updated_at": "2018-11-13T17:44:52Z",
    "url": "https://api.github.com/repos/google/python-adb/issues/134",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/5600962?v=4",
        "events_url": "https://api.github.com/users/penn5/events{/privacy}",
        "followers_url": "https://api.github.com/users/penn5/followers",
        "following_url": "https://api.github.com/users/penn5/following{/other_user}",
        "gists_url": "https://api.github.com/users/penn5/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/penn5",
        "id": 5600962,
        "login": "penn5",
        "node_id": "MDQ6VXNlcjU2MDA5NjI=",
        "organizations_url": "https://api.github.com/users/penn5/orgs",
        "received_events_url": "https://api.github.com/users/penn5/received_events",
        "repos_url": "https://api.github.com/users/penn5/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/penn5/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/penn5/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/penn5"
    }
}