[
    {
        "author_association": "CONTRIBUTOR",
        "body": "Thanks for opening a new issue - is `gio` available on Fedora 28?  ",
        "created_at": "2018-06-04T20:01:19Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-394480098",
        "id": 394480098,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDM5NDQ4MDA5OA==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/394480098/reactions"
        },
        "updated_at": "2018-06-04T20:01:19Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/394480098",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/734194?v=4",
            "events_url": "https://api.github.com/users/rsese/events{/privacy}",
            "followers_url": "https://api.github.com/users/rsese/followers",
            "following_url": "https://api.github.com/users/rsese/following{/other_user}",
            "gists_url": "https://api.github.com/users/rsese/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/rsese",
            "id": 734194,
            "login": "rsese",
            "node_id": "MDQ6VXNlcjczNDE5NA==",
            "organizations_url": "https://api.github.com/users/rsese/orgs",
            "received_events_url": "https://api.github.com/users/rsese/received_events",
            "repos_url": "https://api.github.com/users/rsese/repos",
            "site_admin": true,
            "starred_url": "https://api.github.com/users/rsese/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/rsese/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/rsese"
        }
    },
    {
        "author_association": "NONE",
        "body": "Yes, `gio` is available and installed by default",
        "created_at": "2018-06-04T20:06:35Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-394481555",
        "id": 394481555,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDM5NDQ4MTU1NQ==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/394481555/reactions"
        },
        "updated_at": "2018-06-04T20:06:35Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/394481555",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/12434847?v=4",
            "events_url": "https://api.github.com/users/Devligue/events{/privacy}",
            "followers_url": "https://api.github.com/users/Devligue/followers",
            "following_url": "https://api.github.com/users/Devligue/following{/other_user}",
            "gists_url": "https://api.github.com/users/Devligue/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/Devligue",
            "id": 12434847,
            "login": "Devligue",
            "node_id": "MDQ6VXNlcjEyNDM0ODQ3",
            "organizations_url": "https://api.github.com/users/Devligue/orgs",
            "received_events_url": "https://api.github.com/users/Devligue/received_events",
            "repos_url": "https://api.github.com/users/Devligue/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/Devligue/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Devligue/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/Devligue"
        }
    },
    {
        "author_association": "CONTRIBUTOR",
        "body": "Hmmm, not sure why it's not working then - any difference if you specifically set an `ELECTRON_TRASH` environment variable to `gio` and then restart Atom?",
        "created_at": "2018-06-05T02:12:33Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-394558057",
        "id": 394558057,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDM5NDU1ODA1Nw==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/394558057/reactions"
        },
        "updated_at": "2018-06-05T02:12:33Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/394558057",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/734194?v=4",
            "events_url": "https://api.github.com/users/rsese/events{/privacy}",
            "followers_url": "https://api.github.com/users/rsese/followers",
            "following_url": "https://api.github.com/users/rsese/following{/other_user}",
            "gists_url": "https://api.github.com/users/rsese/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/rsese",
            "id": 734194,
            "login": "rsese",
            "node_id": "MDQ6VXNlcjczNDE5NA==",
            "organizations_url": "https://api.github.com/users/rsese/orgs",
            "received_events_url": "https://api.github.com/users/rsese/received_events",
            "repos_url": "https://api.github.com/users/rsese/repos",
            "site_admin": true,
            "starred_url": "https://api.github.com/users/rsese/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/rsese/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/rsese"
        }
    },
    {
        "author_association": "NONE",
        "body": "It changes nothing :thinking: \r\n\r\n```\r\n$ gio --version\r\n2.56.1\r\n```\r\n\r\n```\r\necho $ELECTRON_TRASH\r\ngio\r\n```\r\n",
        "created_at": "2018-06-05T22:31:29Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-394881373",
        "id": 394881373,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDM5NDg4MTM3Mw==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/394881373/reactions"
        },
        "updated_at": "2018-06-05T22:32:52Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/394881373",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/12434847?v=4",
            "events_url": "https://api.github.com/users/Devligue/events{/privacy}",
            "followers_url": "https://api.github.com/users/Devligue/followers",
            "following_url": "https://api.github.com/users/Devligue/following{/other_user}",
            "gists_url": "https://api.github.com/users/Devligue/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/Devligue",
            "id": 12434847,
            "login": "Devligue",
            "node_id": "MDQ6VXNlcjEyNDM0ODQ3",
            "organizations_url": "https://api.github.com/users/Devligue/orgs",
            "received_events_url": "https://api.github.com/users/Devligue/received_events",
            "repos_url": "https://api.github.com/users/Devligue/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/Devligue/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Devligue/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/Devligue"
        }
    },
    {
        "author_association": "CONTRIBUTOR",
        "body": "And if you just use `gio trash` from the command line it works fine?  E.g.:\r\n\r\n```\r\necho hello > delete-me.txt\r\ngio trash delete-me.txt\r\n```\r\n\r\nAlso, are you getting the exact same error message you mentioned (\"When trying, the following message appears: Is gvfs-trash installed?\") after you set the `ELECTRON_TRASH` environment variable to `gio`?  ",
        "created_at": "2018-06-11T21:35:37Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-396394998",
        "id": 396394998,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDM5NjM5NDk5OA==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 1,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 1,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/396394998/reactions"
        },
        "updated_at": "2018-06-11T21:35:37Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/396394998",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/734194?v=4",
            "events_url": "https://api.github.com/users/rsese/events{/privacy}",
            "followers_url": "https://api.github.com/users/rsese/followers",
            "following_url": "https://api.github.com/users/rsese/following{/other_user}",
            "gists_url": "https://api.github.com/users/rsese/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/rsese",
            "id": 734194,
            "login": "rsese",
            "node_id": "MDQ6VXNlcjczNDE5NA==",
            "organizations_url": "https://api.github.com/users/rsese/orgs",
            "received_events_url": "https://api.github.com/users/rsese/received_events",
            "repos_url": "https://api.github.com/users/rsese/repos",
            "site_admin": true,
            "starred_url": "https://api.github.com/users/rsese/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/rsese/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/rsese"
        }
    },
    {
        "author_association": "NONE",
        "body": "The `echo hello > delete-me.txt; gio trash delete-me.txt` works just fine normally but crashes on the ntfs partition. As I see this, it is not an Atom bug, however the error message it kept returning me was quite misleading.\r\n\r\nI didn't solve the problem yet, but I am closing this since it is not related to Atom. Sorry for trouble!",
        "created_at": "2018-06-11T22:28:55Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-396407349",
        "id": 396407349,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDM5NjQwNzM0OQ==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 1,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 1,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/396407349/reactions"
        },
        "updated_at": "2018-06-11T22:28:55Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/396407349",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/12434847?v=4",
            "events_url": "https://api.github.com/users/Devligue/events{/privacy}",
            "followers_url": "https://api.github.com/users/Devligue/followers",
            "following_url": "https://api.github.com/users/Devligue/following{/other_user}",
            "gists_url": "https://api.github.com/users/Devligue/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/Devligue",
            "id": 12434847,
            "login": "Devligue",
            "node_id": "MDQ6VXNlcjEyNDM0ODQ3",
            "organizations_url": "https://api.github.com/users/Devligue/orgs",
            "received_events_url": "https://api.github.com/users/Devligue/received_events",
            "repos_url": "https://api.github.com/users/Devligue/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/Devligue/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Devligue/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/Devligue"
        }
    },
    {
        "author_association": "CONTRIBUTOR",
        "body": "> however the error message it kept returning me was quite misleading.\r\n\r\nYeah, that's the default error message.  Unfortunately, Electron's moveToTrash method doesn't say _why_ it failed, just that it did.  We've found that the most common reason is that `gvfs-trash` isn't installed, which is why we decided to include it in the error message.",
        "created_at": "2018-06-12T01:13:03Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-396434252",
        "id": 396434252,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDM5NjQzNDI1Mg==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/396434252/reactions"
        },
        "updated_at": "2018-06-12T01:13:03Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/396434252",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/2766036?v=4",
            "events_url": "https://api.github.com/users/50Wliu/events{/privacy}",
            "followers_url": "https://api.github.com/users/50Wliu/followers",
            "following_url": "https://api.github.com/users/50Wliu/following{/other_user}",
            "gists_url": "https://api.github.com/users/50Wliu/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/50Wliu",
            "id": 2766036,
            "login": "50Wliu",
            "node_id": "MDQ6VXNlcjI3NjYwMzY=",
            "organizations_url": "https://api.github.com/users/50Wliu/orgs",
            "received_events_url": "https://api.github.com/users/50Wliu/received_events",
            "repos_url": "https://api.github.com/users/50Wliu/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/50Wliu/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/50Wliu/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/50Wliu"
        }
    },
    {
        "author_association": "NONE",
        "body": "@Devligue This is a legit bug. The _tldr answer_ is that `_g_file_trash` may not be supported. In order for `_g_file_trash` to succeed, the following conditions must be met:\r\n\r\n- The file being moved to trash is on the same partition as your home folder\r\n**OR**\r\n- A trash folder already exists or can be created at the mount point and,\r\n- The trash folder is considered 'safe/secure' by verifying UID and restrictive permissions\r\n\r\n**How this should probably be fixed...**\r\n\r\nAtom does not have a fallback mechanism like offering the ability to permanently remove a file instead. This would address bring atom in line with gnome's graceful behaviour. The attached image show how  Gnome Files (aka Nautilus) prompt the user to permanently delete the file (when trash not supported)\r\n\r\n![gnome's solution](https://user-images.githubusercontent.com/19512121/43511743-0dac32c0-952e-11e8-8af8-e0ef6cb916d0.png)\r\n\r\n**Impact: Users with multiple disks and partitions**\r\n\r\nFedora/Redhat/etc: _Impacted_ due to default partition scheme that separates `/` and `/home` in to partitions. Files outside of the `/home` partition cannot be moved to trash.\r\n\r\nUbuntu: Less likely due to partition layout (`/home` is part of the `/` partition)\r\n\r\nConditions where users will be impacted:\r\n- File systems with unix permissions:\r\n  - _Impacted with workaround_ due to typical restrictive top-level directory permissions (root)\r\n- FAT/non-unix file systems:\r\n  - User Session Mount (i.e. `/run/media/$USER/disk-label`): _No Impact_\r\n  - Fstab: _Impacted_ even with permissive umask. The default uid/gid is root. It will be unable to satisfy the requirements of a trash folder without additional options (uid/gid/umask).\r\n- Network shared folders: _Unknown/Did not test._\r\n\r\n**Notes/Testing the Root Cause**\r\n\r\nNote: Though I am confident that my analysis is decent enough, much of the code I was referencing was unfamiliar/new to me.\r\n\r\nInitially I encountered this issue when I put files in a certain location like the reporter above. I created a delete-me file test as suggested above in the relevant directory, `/opt/cupenv`. I ran the command  `strace gio trash delete-me.txt`. A abridged version of the output is here:\r\n\r\n```\r\nlstat(\"/opt/cupenv/delete-me.txt\", {st_mode=S_IFREG|0664, st_size=6, ...}) = 0\r\n...\r\nlstat(\"/.Trash-1000\", 0x7ffde5ffb5b0)   = -1 ENOENT (No such file or directory)\r\nmkdir(\"/.Trash-1000\", 0700)             = -1 EACCES (Permission denied)\r\n```\r\nThat's unexpected. The API documentation for [g_file_trash](https://developer.gnome.org/gio/stable/GFile.html#g-file-trash) lacks some level of specificity.\r\n\r\n> Sends file to the \"Trashcan\", if possible. This is similar to deleting it, but the user can recover it before emptying the trashcan. Not all file systems support trashing, so this call can return the G_IO_ERROR_NOT_SUPPORTED error. \r\n\r\nOne might assume (as I did): Given a path, if the user has permission to modify/delete the file, then GIO's g_file_trash API should succeed at removing the file in some manner. Perhaps, if trash functionality is not available, then there might be a fallback mechanism. In the case of `gio trash` I expected there to be a -f force option that would prioritize trash over permanently deleting the file. (`gio trash -f` only ignores files that don't exist)\r\n\r\nGlib appears to implement GIO local file access using [glocalfile.c](https://github.com/GNOME/glib/blob/83a4cab12c2d00dbfe6013d071cff2da310109a4/gio/glocalfile.c#L1899). The trash algorithm looks like this:\r\n\r\n- Is the path on the same partition as the user's home directory? If so, move the file to the home trash folder if possible and exit.\r\n- Given the path, locate the mount point top level directory (denoted as `$topdir` in source)\r\n  - In my case, `/opt/cupenv/delete_me.txt` -> `/` (the primary partition)\r\n  - A more typical case: `/run/media/$USER/disk-label/a/b/c/d` would be `/run/media/$USER/disk-label`\r\n- If `$topdir` is found, pick one of `$topdir/.Trash/$UID` or `$topdir/.Trash-UID` folder.\r\n  - If `$topdir/.Trash-UID` and `$topdir/.Trash/$UID` exists: Validate proper UID and file permission (or fail)\r\n  - Try to create folder `$topdir/.Trash-$UID`. Validate proper UID and file permission (or fail)\r\n\r\nAt the end of the function we find [`G_IO_ERROR_NOT_SUPPORTED` is returned](https://github.com/GNOME/glib/blob/83a4cab12c2d00dbfe6013d071cff2da310109a4/gio/glocalfile.c#L2059) when such a folder is not found and cannot be created.\r\n\r\n```\r\nif (trashdir == NULL)\r\n\t{\r\n\t  g_free (topdir);\r\n          g_set_io_error (error,\r\n                          _(\"Unable to find or create trash directory for %s\"),\r\n                          file, G_IO_ERROR_NOT_SUPPORTED);\r\n\t  return FALSE;\r\n}\r\n```\r\n\r\nI confirmed my understanding by creating a top level trash folder and using gio trash command.\r\n\r\n```\r\nsudo mkdir /.Trash-1000\r\nsudo chmod 0700 /.Trash-1000\r\nsudo chown fosterb:fosterb /.Trash-1000\r\ncd /opt/cupenv && echo hello > delete-me.txt; gio trash delete-me.txt\r\n```\r\nFiles located on the same partition as your home directory can always be moved to your user trash folder. On my operating system, the paths `/` and `/home` are separate partitions. I created a file `/home/tmp/x` where `tmp` and `x` are owned by my user. In this case, the files get moved to your `$HOME/.local/share/Trash` folder.\r\n\r\n```\r\nlstat(\"/home/tmp/x\", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0\r\nstat(\"/home/fosterb\", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0\r\naccess(\"/home\", F_OK)                   = 0\r\n....\r\nstat(\"/home/fosterb/.local/share\", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0\r\naccess(\"/home/fosterb/.local/share/Trash\", F_OK) = 0\r\nstat(\"/home/fosterb/.local/share/Trash\", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0\r\nmkdir(\"/home/fosterb/.local/share/Trash/info\", 0700) = -1 EEXIST (File exists)\r\nmkdir(\"/home/fosterb/.local/share/Trash/files\", 0700) = -1 EEXIST (File exists)\r\nopenat(AT_FDCWD, \"/home/fosterb/.local/share/Trash/info/x.trashinfo\", O_RDONLY|O_CREAT|O_EXCL, 0666) = 7\r\n```\r\nBut when mounting disks (external or internal) using fstab or mount commands (as opposed to session-based mounting) issues can arise. I tested a FAT file system with umask=0000 and uid/gid set to root.\r\n\r\n```\r\nlstat(\"/mnt/giotest\", {st_mode=S_IFDIR|0777, st_size=8192, ...}) = 0\r\nlstat(\"/mnt\", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0\r\nlstat(\"/mnt/giotest/.Trash\", 0x7fffec5502c0) = -1 ENOENT (No such file or directory)\r\nlstat(\"/mnt/giotest/.Trash-1000\", 0x7fffec550230) = -1 ENOENT (No such file or directory)\r\nmkdir(\"/mnt/giotest/.Trash-1000\", 0700) = 0\r\nlstat(\"/mnt/giotest/.Trash-1000\", {st_mode=S_IFDIR|0777, st_size=8192, ...}) = 0\r\nunlink(\"/mnt/giotest/.Trash-1000\")      = -1 EISDIR (Is a directory)\r\nrmdir(\"/mnt/giotest/.Trash-1000\")       = 0\r\nfile:///mnt/giotest/x: Unable to find or create trash directory for /mnt/giotest/x\r\n```\r\n\r\nYou can see gio trash going through the motions. The operations succeeds but the command still reports an error.\r\n```\r\n[fosterb@rose giotest]$ ls -lah\r\ntotal 12K\r\ndrwxrwxrwx. 2 root root 8.0K Aug  1 00:36 .\r\ndrwxr-xr-x. 4 root root 4.0K Aug  1 00:30 ..\r\n-rwxrwxrwx. 1 root root    0 Aug  1 01:23 x\r\n```\r\n\r\nGLib/Gio will not write to a trash directory with incorrect permissions/ownership. (Security?) Without unix permissions, trash will always fail on these mount points. Modifying fstab to appear similar to options used during session mounts (UID/GID set to user vs root, umask is set appropriately). Conveniently the [source code](https://github.com/GNOME/glib/blob/83a4cab12c2d00dbfe6013d071cff2da310109a4/gio/glocalfile.c#L2046) has a comment that seems to strongly imply this is a known/expected.\r\n\r\n```\r\n\t\t  /* Ensure that the created dir has the right uid etc.\r\n\t\t     This might fail on e.g. a FAT dir */\r\n```\r\nMost of this was unnecessary, but I figured I'd show my work.",
        "created_at": "2018-08-01T09:48:16Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-409518547",
        "id": 409518547,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDQwOTUxODU0Nw==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 2,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 2,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/409518547/reactions"
        },
        "updated_at": "2018-08-16T00:32:01Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/409518547",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/19512121?v=4",
            "events_url": "https://api.github.com/users/cutephoton/events{/privacy}",
            "followers_url": "https://api.github.com/users/cutephoton/followers",
            "following_url": "https://api.github.com/users/cutephoton/following{/other_user}",
            "gists_url": "https://api.github.com/users/cutephoton/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/cutephoton",
            "id": 19512121,
            "login": "cutephoton",
            "node_id": "MDQ6VXNlcjE5NTEyMTIx",
            "organizations_url": "https://api.github.com/users/cutephoton/orgs",
            "received_events_url": "https://api.github.com/users/cutephoton/received_events",
            "repos_url": "https://api.github.com/users/cutephoton/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/cutephoton/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/cutephoton/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/cutephoton"
        }
    },
    {
        "author_association": "NONE",
        "body": "I got the same problem on feodra 29 on a fresh install can we reopen this bug ?",
        "created_at": "2018-10-31T22:49:15Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-434874062",
        "id": 434874062,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDQzNDg3NDA2Mg==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 13,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 13,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/434874062/reactions"
        },
        "updated_at": "2018-10-31T22:49:15Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/434874062",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/704477?v=4",
            "events_url": "https://api.github.com/users/yodatak/events{/privacy}",
            "followers_url": "https://api.github.com/users/yodatak/followers",
            "following_url": "https://api.github.com/users/yodatak/following{/other_user}",
            "gists_url": "https://api.github.com/users/yodatak/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/yodatak",
            "id": 704477,
            "login": "yodatak",
            "node_id": "MDQ6VXNlcjcwNDQ3Nw==",
            "organizations_url": "https://api.github.com/users/yodatak/orgs",
            "received_events_url": "https://api.github.com/users/yodatak/received_events",
            "repos_url": "https://api.github.com/users/yodatak/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/yodatak/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/yodatak/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/yodatak"
        }
    },
    {
        "author_association": "NONE",
        "body": "@Devligue can reopen this",
        "created_at": "2018-10-31T23:14:47Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-434879241",
        "id": 434879241,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDQzNDg3OTI0MQ==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/434879241/reactions"
        },
        "updated_at": "2018-10-31T23:14:47Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/434879241",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/19512121?v=4",
            "events_url": "https://api.github.com/users/cutephoton/events{/privacy}",
            "followers_url": "https://api.github.com/users/cutephoton/followers",
            "following_url": "https://api.github.com/users/cutephoton/following{/other_user}",
            "gists_url": "https://api.github.com/users/cutephoton/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/cutephoton",
            "id": 19512121,
            "login": "cutephoton",
            "node_id": "MDQ6VXNlcjE5NTEyMTIx",
            "organizations_url": "https://api.github.com/users/cutephoton/orgs",
            "received_events_url": "https://api.github.com/users/cutephoton/received_events",
            "repos_url": "https://api.github.com/users/cutephoton/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/cutephoton/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/cutephoton/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/cutephoton"
        }
    },
    {
        "author_association": "NONE",
        "body": "This issue has been automatically closed because there has been no response to our request for more information from the original author. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.\n",
        "created_at": "2018-11-01T14:20:10Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-435055127",
        "id": 435055127,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDQzNTA1NTEyNw==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/435055127/reactions"
        },
        "updated_at": "2018-11-01T14:20:10Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/435055127",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/26350515?v=4",
            "events_url": "https://api.github.com/users/no-response%5Bbot%5D/events{/privacy}",
            "followers_url": "https://api.github.com/users/no-response%5Bbot%5D/followers",
            "following_url": "https://api.github.com/users/no-response%5Bbot%5D/following{/other_user}",
            "gists_url": "https://api.github.com/users/no-response%5Bbot%5D/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/apps/no-response",
            "id": 32965360,
            "login": "no-response[bot]",
            "node_id": "MDM6Qm90MzI5NjUzNjA=",
            "organizations_url": "https://api.github.com/users/no-response%5Bbot%5D/orgs",
            "received_events_url": "https://api.github.com/users/no-response%5Bbot%5D/received_events",
            "repos_url": "https://api.github.com/users/no-response%5Bbot%5D/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/no-response%5Bbot%5D/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/no-response%5Bbot%5D/subscriptions",
            "type": "Bot",
            "url": "https://api.github.com/users/no-response%5Bbot%5D"
        }
    },
    {
        "author_association": "NONE",
        "body": "I may have no additional information about the issue, but I am sure @cutephoton provided enough insight. There are also other people who have similar unsolved problems. I am reopening this.",
        "created_at": "2018-11-01T14:52:10Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-435065398",
        "id": 435065398,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDQzNTA2NTM5OA==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 10,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 10,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/435065398/reactions"
        },
        "updated_at": "2018-11-01T14:52:10Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/435065398",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/12434847?v=4",
            "events_url": "https://api.github.com/users/Devligue/events{/privacy}",
            "followers_url": "https://api.github.com/users/Devligue/followers",
            "following_url": "https://api.github.com/users/Devligue/following{/other_user}",
            "gists_url": "https://api.github.com/users/Devligue/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/Devligue",
            "id": 12434847,
            "login": "Devligue",
            "node_id": "MDQ6VXNlcjEyNDM0ODQ3",
            "organizations_url": "https://api.github.com/users/Devligue/orgs",
            "received_events_url": "https://api.github.com/users/Devligue/received_events",
            "repos_url": "https://api.github.com/users/Devligue/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/Devligue/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Devligue/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/Devligue"
        }
    },
    {
        "author_association": "NONE",
        "body": "I got no problem with the flatpak version by the way",
        "created_at": "2018-11-05T22:24:01Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-436058295",
        "id": 436058295,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDQzNjA1ODI5NQ==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/436058295/reactions"
        },
        "updated_at": "2018-11-05T22:24:01Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/436058295",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/704477?v=4",
            "events_url": "https://api.github.com/users/yodatak/events{/privacy}",
            "followers_url": "https://api.github.com/users/yodatak/followers",
            "following_url": "https://api.github.com/users/yodatak/following{/other_user}",
            "gists_url": "https://api.github.com/users/yodatak/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/yodatak",
            "id": 704477,
            "login": "yodatak",
            "node_id": "MDQ6VXNlcjcwNDQ3Nw==",
            "organizations_url": "https://api.github.com/users/yodatak/orgs",
            "received_events_url": "https://api.github.com/users/yodatak/received_events",
            "repos_url": "https://api.github.com/users/yodatak/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/yodatak/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/yodatak/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/yodatak"
        }
    },
    {
        "author_association": "NONE",
        "body": "I reproduced on the latest version still. **shrug** I don't see how flatpak and rpm/deb would differ. It only fails when the preconditions listed above are met -- a partition where you don't have permission to create a trash folder under your user ID.",
        "created_at": "2018-11-06T00:54:29Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-436091788",
        "id": 436091788,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDQzNjA5MTc4OA==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/436091788/reactions"
        },
        "updated_at": "2018-11-06T00:54:29Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/436091788",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/19512121?v=4",
            "events_url": "https://api.github.com/users/cutephoton/events{/privacy}",
            "followers_url": "https://api.github.com/users/cutephoton/followers",
            "following_url": "https://api.github.com/users/cutephoton/following{/other_user}",
            "gists_url": "https://api.github.com/users/cutephoton/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/cutephoton",
            "id": 19512121,
            "login": "cutephoton",
            "node_id": "MDQ6VXNlcjE5NTEyMTIx",
            "organizations_url": "https://api.github.com/users/cutephoton/orgs",
            "received_events_url": "https://api.github.com/users/cutephoton/received_events",
            "repos_url": "https://api.github.com/users/cutephoton/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/cutephoton/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/cutephoton/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/cutephoton"
        }
    },
    {
        "author_association": "NONE",
        "body": "With flatpak i got no error but it don't get delete sorry about this misinformation. I try to disable selinux it don't change.",
        "created_at": "2018-11-06T21:31:27Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-436415808",
        "id": 436415808,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDQzNjQxNTgwOA==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/436415808/reactions"
        },
        "updated_at": "2018-11-06T21:32:54Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/436415808",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/704477?v=4",
            "events_url": "https://api.github.com/users/yodatak/events{/privacy}",
            "followers_url": "https://api.github.com/users/yodatak/followers",
            "following_url": "https://api.github.com/users/yodatak/following{/other_user}",
            "gists_url": "https://api.github.com/users/yodatak/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/yodatak",
            "id": 704477,
            "login": "yodatak",
            "node_id": "MDQ6VXNlcjcwNDQ3Nw==",
            "organizations_url": "https://api.github.com/users/yodatak/orgs",
            "received_events_url": "https://api.github.com/users/yodatak/received_events",
            "repos_url": "https://api.github.com/users/yodatak/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/yodatak/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/yodatak/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/yodatak"
        }
    },
    {
        "author_association": "NONE",
        "body": "No. Not selinux. It has to do with how trash folders work. My rather verbose explanation gets in to the nitty gritty for where atom's behavior is deficient.  The short answer is that atom only asks to move files to trash and does not delete files. If a trash folder cannot be created (multiple causes all related to permissions) than it fails. Atom should inquire with user if they should permanently delete the files instead of failing.  ",
        "created_at": "2018-11-06T21:48:03Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-436420632",
        "id": 436420632,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDQzNjQyMDYzMg==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/436420632/reactions"
        },
        "updated_at": "2018-11-06T21:48:03Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/436420632",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/19512121?v=4",
            "events_url": "https://api.github.com/users/cutephoton/events{/privacy}",
            "followers_url": "https://api.github.com/users/cutephoton/followers",
            "following_url": "https://api.github.com/users/cutephoton/following{/other_user}",
            "gists_url": "https://api.github.com/users/cutephoton/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/cutephoton",
            "id": 19512121,
            "login": "cutephoton",
            "node_id": "MDQ6VXNlcjE5NTEyMTIx",
            "organizations_url": "https://api.github.com/users/cutephoton/orgs",
            "received_events_url": "https://api.github.com/users/cutephoton/received_events",
            "repos_url": "https://api.github.com/users/cutephoton/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/cutephoton/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/cutephoton/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/cutephoton"
        }
    },
    {
        "author_association": "NONE",
        "body": "As @yodatak also mentioned that Fedora 29 fresh install has this problem since `gvfs-trash` has finally after many deprecation notices been removed  and replaced with  `gio`. So as @rsese mentioned you need to set `ELECTRON_TRASH=gio` e.g. add it to your `~/.bash_profile`. \r\n\r\nlogout and login or `source ~/.bash_profile` and trashing will work\r\n\r\nor\r\n```\r\necho 'export ELECTRON_TRASH=gio' >> $HOME/.bashrc\r\nsource $HOME/.bashrc\r\n```",
        "created_at": "2018-11-13T11:29:03Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-438233353",
        "id": 438233353,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDQzODIzMzM1Mw==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 14,
            "-1": 1,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 15,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/438233353/reactions"
        },
        "updated_at": "2019-04-19T17:50:15Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/438233353",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/15878458?v=4",
            "events_url": "https://api.github.com/users/mkungla/events{/privacy}",
            "followers_url": "https://api.github.com/users/mkungla/followers",
            "following_url": "https://api.github.com/users/mkungla/following{/other_user}",
            "gists_url": "https://api.github.com/users/mkungla/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/mkungla",
            "id": 15878458,
            "login": "mkungla",
            "node_id": "MDQ6VXNlcjE1ODc4NDU4",
            "organizations_url": "https://api.github.com/users/mkungla/orgs",
            "received_events_url": "https://api.github.com/users/mkungla/received_events",
            "repos_url": "https://api.github.com/users/mkungla/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/mkungla/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mkungla/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/mkungla"
        }
    },
    {
        "author_association": "NONE",
        "body": "Gio operates the same way. I used the Gio command line to manually step through this...",
        "created_at": "2018-11-13T12:54:30Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-438255687",
        "id": 438255687,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDQzODI1NTY4Nw==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/438255687/reactions"
        },
        "updated_at": "2018-11-13T12:54:30Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/438255687",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/19512121?v=4",
            "events_url": "https://api.github.com/users/cutephoton/events{/privacy}",
            "followers_url": "https://api.github.com/users/cutephoton/followers",
            "following_url": "https://api.github.com/users/cutephoton/following{/other_user}",
            "gists_url": "https://api.github.com/users/cutephoton/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/cutephoton",
            "id": 19512121,
            "login": "cutephoton",
            "node_id": "MDQ6VXNlcjE5NTEyMTIx",
            "organizations_url": "https://api.github.com/users/cutephoton/orgs",
            "received_events_url": "https://api.github.com/users/cutephoton/received_events",
            "repos_url": "https://api.github.com/users/cutephoton/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/cutephoton/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/cutephoton/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/cutephoton"
        }
    },
    {
        "author_association": "NONE",
        "body": "running fedora 29, i have installed atom from packages, since recently I faced the same error as described here.\r\n\r\n```\r\nsudo dnf list installed atom\r\nPaquets install\u00e9s\r\natom.x86_64                                                1.33.0-0.1                                                 @Atom\r\n```\r\n\r\nI think this bug deserves an action in order to improve the package installation, or the runtime, to detect gio/gvfs and make this work out of the box.\r\n\r\nThis really is an ugly bug for the end user experience.",
        "created_at": "2018-12-06T12:06:34Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-444849970",
        "id": 444849970,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ0NDg0OTk3MA==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 8,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 8,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/444849970/reactions"
        },
        "updated_at": "2018-12-06T12:06:34Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/444849970",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/17096799?v=4",
            "events_url": "https://api.github.com/users/mh-cbon/events{/privacy}",
            "followers_url": "https://api.github.com/users/mh-cbon/followers",
            "following_url": "https://api.github.com/users/mh-cbon/following{/other_user}",
            "gists_url": "https://api.github.com/users/mh-cbon/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/mh-cbon",
            "id": 17096799,
            "login": "mh-cbon",
            "node_id": "MDQ6VXNlcjE3MDk2Nzk5",
            "organizations_url": "https://api.github.com/users/mh-cbon/orgs",
            "received_events_url": "https://api.github.com/users/mh-cbon/received_events",
            "repos_url": "https://api.github.com/users/mh-cbon/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/mh-cbon/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mh-cbon/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/mh-cbon"
        }
    },
    {
        "author_association": "NONE",
        "body": "Is there any workaround to delete files with Atom on Fedora 29?",
        "created_at": "2018-12-09T12:32:04Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-445533825",
        "id": 445533825,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ0NTUzMzgyNQ==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 1,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 1,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/445533825/reactions"
        },
        "updated_at": "2018-12-09T12:32:04Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/445533825",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/27968888?v=4",
            "events_url": "https://api.github.com/users/cristianlivella/events{/privacy}",
            "followers_url": "https://api.github.com/users/cristianlivella/followers",
            "following_url": "https://api.github.com/users/cristianlivella/following{/other_user}",
            "gists_url": "https://api.github.com/users/cristianlivella/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/cristianlivella",
            "id": 27968888,
            "login": "cristianlivella",
            "node_id": "MDQ6VXNlcjI3OTY4ODg4",
            "organizations_url": "https://api.github.com/users/cristianlivella/orgs",
            "received_events_url": "https://api.github.com/users/cristianlivella/received_events",
            "repos_url": "https://api.github.com/users/cristianlivella/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/cristianlivella/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/cristianlivella/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/cristianlivella"
        }
    },
    {
        "author_association": "NONE",
        "body": "> So as @rsese mentioned you need to set `ELECTRON_TRASH=gio` e.g. add it to your `~/.bash_profile`.\r\n> \r\n> logout and login or `source ~/.bash_profile` and trashing will work\r\n\r\nThis is not working on fedora 29, even with gio installed and ELECTRON_TRASH variable set to gio.",
        "created_at": "2018-12-12T08:32:45Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-446504315",
        "id": 446504315,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ0NjUwNDMxNQ==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 1,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 1,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/446504315/reactions"
        },
        "updated_at": "2018-12-12T08:32:45Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/446504315",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/1556109?v=4",
            "events_url": "https://api.github.com/users/edlefebvre/events{/privacy}",
            "followers_url": "https://api.github.com/users/edlefebvre/followers",
            "following_url": "https://api.github.com/users/edlefebvre/following{/other_user}",
            "gists_url": "https://api.github.com/users/edlefebvre/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/edlefebvre",
            "id": 1556109,
            "login": "edlefebvre",
            "node_id": "MDQ6VXNlcjE1NTYxMDk=",
            "organizations_url": "https://api.github.com/users/edlefebvre/orgs",
            "received_events_url": "https://api.github.com/users/edlefebvre/received_events",
            "repos_url": "https://api.github.com/users/edlefebvre/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/edlefebvre/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/edlefebvre/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/edlefebvre"
        }
    },
    {
        "author_association": "NONE",
        "body": "There are no workarounds.",
        "created_at": "2018-12-12T14:03:28Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-446598217",
        "id": 446598217,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ0NjU5ODIxNw==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/446598217/reactions"
        },
        "updated_at": "2018-12-12T14:03:28Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/446598217",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/19512121?v=4",
            "events_url": "https://api.github.com/users/cutephoton/events{/privacy}",
            "followers_url": "https://api.github.com/users/cutephoton/followers",
            "following_url": "https://api.github.com/users/cutephoton/following{/other_user}",
            "gists_url": "https://api.github.com/users/cutephoton/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/cutephoton",
            "id": 19512121,
            "login": "cutephoton",
            "node_id": "MDQ6VXNlcjE5NTEyMTIx",
            "organizations_url": "https://api.github.com/users/cutephoton/orgs",
            "received_events_url": "https://api.github.com/users/cutephoton/received_events",
            "repos_url": "https://api.github.com/users/cutephoton/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/cutephoton/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/cutephoton/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/cutephoton"
        }
    },
    {
        "author_association": "NONE",
        "body": "> > So as @rsese mentioned you need to set `ELECTRON_TRASH=gio` e.g. add it to your `~/.bash_profile`.\r\n> > logout and login or `source ~/.bash_profile` and trashing will work\r\n> \r\n> This is not working on fedora 29, even with gio installed and ELECTRON_TRASH variable set to gio.\r\n\r\nWorks on my Fedora 29 -- had to restart terminal and restart atom from that terminal.",
        "created_at": "2018-12-17T19:44:08Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-447973447",
        "id": 447973447,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ0Nzk3MzQ0Nw==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 2,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 2,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/447973447/reactions"
        },
        "updated_at": "2018-12-17T19:44:08Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/447973447",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/681067?v=4",
            "events_url": "https://api.github.com/users/olegjs/events{/privacy}",
            "followers_url": "https://api.github.com/users/olegjs/followers",
            "following_url": "https://api.github.com/users/olegjs/following{/other_user}",
            "gists_url": "https://api.github.com/users/olegjs/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/olegjs",
            "id": 681067,
            "login": "olegjs",
            "node_id": "MDQ6VXNlcjY4MTA2Nw==",
            "organizations_url": "https://api.github.com/users/olegjs/orgs",
            "received_events_url": "https://api.github.com/users/olegjs/received_events",
            "repos_url": "https://api.github.com/users/olegjs/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/olegjs/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/olegjs/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/olegjs"
        }
    },
    {
        "author_association": "NONE",
        "body": "That is a not a fix. There are preconditions as documented above to reproduce the bug.",
        "created_at": "2018-12-17T20:30:24Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-447988001",
        "id": 447988001,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ0Nzk4ODAwMQ==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/447988001/reactions"
        },
        "updated_at": "2018-12-17T20:30:24Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/447988001",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/19512121?v=4",
            "events_url": "https://api.github.com/users/cutephoton/events{/privacy}",
            "followers_url": "https://api.github.com/users/cutephoton/followers",
            "following_url": "https://api.github.com/users/cutephoton/following{/other_user}",
            "gists_url": "https://api.github.com/users/cutephoton/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/cutephoton",
            "id": 19512121,
            "login": "cutephoton",
            "node_id": "MDQ6VXNlcjE5NTEyMTIx",
            "organizations_url": "https://api.github.com/users/cutephoton/orgs",
            "received_events_url": "https://api.github.com/users/cutephoton/received_events",
            "repos_url": "https://api.github.com/users/cutephoton/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/cutephoton/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/cutephoton/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/cutephoton"
        }
    },
    {
        "author_association": "NONE",
        "body": "Would love for this to be fixed (on my Fedora 29 installed via the official RPM).",
        "created_at": "2018-12-28T08:30:30Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-450317039",
        "id": 450317039,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ1MDMxNzAzOQ==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 1,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 1,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/450317039/reactions"
        },
        "updated_at": "2018-12-28T08:30:30Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/450317039",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/8958906?v=4",
            "events_url": "https://api.github.com/users/shivdhar/events{/privacy}",
            "followers_url": "https://api.github.com/users/shivdhar/followers",
            "following_url": "https://api.github.com/users/shivdhar/following{/other_user}",
            "gists_url": "https://api.github.com/users/shivdhar/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/shivdhar",
            "id": 8958906,
            "login": "shivdhar",
            "node_id": "MDQ6VXNlcjg5NTg5MDY=",
            "organizations_url": "https://api.github.com/users/shivdhar/orgs",
            "received_events_url": "https://api.github.com/users/shivdhar/received_events",
            "repos_url": "https://api.github.com/users/shivdhar/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/shivdhar/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/shivdhar/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/shivdhar"
        }
    },
    {
        "author_association": "NONE",
        "body": "This bug is also affecting me on a fresh install of Fedora 29 and Atom 1.33.1.\r\n\r\nIf I try to delete a file within atom, I get the following error:\r\n![gvfs-gio-error](https://user-images.githubusercontent.com/5628330/50742193-8be3d980-11bc-11e9-9d98-8c307d563839.png)\r\n\r\nIf I use gio on the command line:\r\n```\r\n$ gio trash /home/bauthier/Tools/ansible_local/roles/work_packages/files/test.txt\r\n$\r\n```\r\nno issue and it deletes as expected.\r\n\r\nMy system partitions are broken up like so:\r\n```\r\n$ df -h\r\nFilesystem               Size  Used Avail Use% Mounted on\r\ndevtmpfs                 7.8G     0  7.8G   0% /dev\r\ntmpfs                    7.8G  225M  7.6G   3% /dev/shm\r\ntmpfs                    7.8G  2.0M  7.8G   1% /run\r\ntmpfs                    7.8G     0  7.8G   0% /sys/fs/cgroup\r\n/dev/mapper/fedora-root   49G   11G   36G  24% /\r\ntmpfs                    7.8G  236K  7.8G   1% /tmp\r\n/dev/sda2                976M  160M  750M  18% /boot\r\n/dev/mapper/fedora-home  414G  892M  392G   1% /home\r\n/dev/sda1               1022M   21M 1002M   3% /boot/efi\r\ntmpfs                    1.6G  8.4M  1.6G   1% /run/user/1000\r\n```\r\nIf I explicitly set an environment variable like this within my **~/.bashrc**:\r\n```\r\nexport ELECTRON_TRASH=gio\r\n```\r\nit does delete within atom correctly.\r\n\r\nHaving to set this environment variable is less than ideal. I read through cutephoton's research, testing, and analysis and I believe mine works because **/home** and **/** are on different mounts, but the same partition. Perhaps LVM versus standard partitions?\r\n\r\nEither way, I would imagine the handling of \"gvfs\" or \"gio\" would be done by atom and set correctly during start time of the application. I haven't read through the atom code so there may have been a reason to couple that functionality to \"gvfs\" rather than dynamically choosing a suitable trash program and application startup.\r\n",
        "created_at": "2019-01-06T22:47:58Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-451782512",
        "id": 451782512,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ1MTc4MjUxMg==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 5,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 5,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/451782512/reactions"
        },
        "updated_at": "2019-01-06T22:47:58Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/451782512",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/5628330?v=4",
            "events_url": "https://api.github.com/users/histamineblkr/events{/privacy}",
            "followers_url": "https://api.github.com/users/histamineblkr/followers",
            "following_url": "https://api.github.com/users/histamineblkr/following{/other_user}",
            "gists_url": "https://api.github.com/users/histamineblkr/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/histamineblkr",
            "id": 5628330,
            "login": "histamineblkr",
            "node_id": "MDQ6VXNlcjU2MjgzMzA=",
            "organizations_url": "https://api.github.com/users/histamineblkr/orgs",
            "received_events_url": "https://api.github.com/users/histamineblkr/received_events",
            "repos_url": "https://api.github.com/users/histamineblkr/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/histamineblkr/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/histamineblkr/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/histamineblkr"
        }
    },
    {
        "author_association": "NONE",
        "body": "https://github.com/electron/electron/issues/15011\r\n",
        "created_at": "2019-01-06T23:11:32Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-451784280",
        "id": 451784280,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ1MTc4NDI4MA==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 1,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 1,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/451784280/reactions"
        },
        "updated_at": "2019-01-06T23:11:32Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/451784280",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/704477?v=4",
            "events_url": "https://api.github.com/users/yodatak/events{/privacy}",
            "followers_url": "https://api.github.com/users/yodatak/followers",
            "following_url": "https://api.github.com/users/yodatak/following{/other_user}",
            "gists_url": "https://api.github.com/users/yodatak/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/yodatak",
            "id": 704477,
            "login": "yodatak",
            "node_id": "MDQ6VXNlcjcwNDQ3Nw==",
            "organizations_url": "https://api.github.com/users/yodatak/orgs",
            "received_events_url": "https://api.github.com/users/yodatak/received_events",
            "repos_url": "https://api.github.com/users/yodatak/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/yodatak/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/yodatak/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/yodatak"
        }
    },
    {
        "author_association": "NONE",
        "body": "same here with fedora 29 and atom 1.34.0\r\n\r\nthat workaround has helped me https://github.com/atom/atom/issues/15949#issuecomment-434231263",
        "created_at": "2019-01-11T08:44:24Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-453432839",
        "id": 453432839,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ1MzQzMjgzOQ==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 5,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 4,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 9,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/453432839/reactions"
        },
        "updated_at": "2019-01-11T08:44:24Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/453432839",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/5287237?v=4",
            "events_url": "https://api.github.com/users/den-is/events{/privacy}",
            "followers_url": "https://api.github.com/users/den-is/followers",
            "following_url": "https://api.github.com/users/den-is/following{/other_user}",
            "gists_url": "https://api.github.com/users/den-is/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/den-is",
            "id": 5287237,
            "login": "den-is",
            "node_id": "MDQ6VXNlcjUyODcyMzc=",
            "organizations_url": "https://api.github.com/users/den-is/orgs",
            "received_events_url": "https://api.github.com/users/den-is/received_events",
            "repos_url": "https://api.github.com/users/den-is/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/den-is/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/den-is/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/den-is"
        }
    },
    {
        "author_association": "NONE",
        "body": "same here with fedora 29 and atom 1.33.0x64\r\n`~$ lsb_release -a`\r\n```\r\nLSB Version:\t:core-4.1-amd64:core-4.1-noarch\r\nDistributor ID:\tFedora\r\nDescription:\tFedora release 29 (Twenty Nine)\r\nRelease:\t29\r\nCodename:\tTwentyNine\r\n```",
        "created_at": "2019-01-14T12:58:36Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-453996220",
        "id": 453996220,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ1Mzk5NjIyMA==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 0,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 0,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/453996220/reactions"
        },
        "updated_at": "2019-01-14T12:59:23Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/453996220",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/15796342?v=4",
            "events_url": "https://api.github.com/users/abudawud/events{/privacy}",
            "followers_url": "https://api.github.com/users/abudawud/followers",
            "following_url": "https://api.github.com/users/abudawud/following{/other_user}",
            "gists_url": "https://api.github.com/users/abudawud/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/abudawud",
            "id": 15796342,
            "login": "abudawud",
            "node_id": "MDQ6VXNlcjE1Nzk2MzQy",
            "organizations_url": "https://api.github.com/users/abudawud/orgs",
            "received_events_url": "https://api.github.com/users/abudawud/received_events",
            "repos_url": "https://api.github.com/users/abudawud/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/abudawud/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/abudawud/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/abudawud"
        }
    },
    {
        "author_association": "NONE",
        "body": "> @histamineblkr If I explicitly set an environment variable like this within my **~/.bashrc**:\r\n> \r\n> ```\r\n> export ELECTRON_TRASH=gio\r\n> ```\r\n\r\nThis did work for me, in Fedora 29. ",
        "created_at": "2019-01-27T22:23:37Z",
        "html_url": "https://github.com/atom/atom/issues/17452#issuecomment-457959922",
        "id": 457959922,
        "issue_url": "https://api.github.com/repos/atom/atom/issues/17452",
        "node_id": "MDEyOklzc3VlQ29tbWVudDQ1Nzk1OTkyMg==",
        "performed_via_github_app": null,
        "reactions": {
            "+1": 1,
            "-1": 0,
            "confused": 0,
            "eyes": 0,
            "heart": 0,
            "hooray": 0,
            "laugh": 0,
            "rocket": 0,
            "total_count": 1,
            "url": "https://api.github.com/repos/atom/atom/issues/comments/457959922/reactions"
        },
        "updated_at": "2019-01-27T22:23:37Z",
        "url": "https://api.github.com/repos/atom/atom/issues/comments/457959922",
        "user": {
            "avatar_url": "https://avatars.githubusercontent.com/u/9272498?v=4",
            "events_url": "https://api.github.com/users/nelson6e65/events{/privacy}",
            "followers_url": "https://api.github.com/users/nelson6e65/followers",
            "following_url": "https://api.github.com/users/nelson6e65/following{/other_user}",
            "gists_url": "https://api.github.com/users/nelson6e65/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/nelson6e65",
            "id": 9272498,
            "login": "nelson6e65",
            "node_id": "MDQ6VXNlcjkyNzI0OTg=",
            "organizations_url": "https://api.github.com/users/nelson6e65/orgs",
            "received_events_url": "https://api.github.com/users/nelson6e65/received_events",
            "repos_url": "https://api.github.com/users/nelson6e65/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/nelson6e65/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/nelson6e65/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/nelson6e65"
        }
    }
]